name       : perl-path-tiny
version    : '0.108'
release    : 5
source     :
    - https://github.com/dagolden/Path-Tiny/archive/release-0.108.tar.gz : 45ea5ed9fafb322a3ee8010bb89294c4afe5fd81cb2f090fedb9229646e6eb35
license    : Apache-2.0
component  : programming.perl
homepage   : https://github.com/dagolden/Path-Tiny
summary    : Path::Tiny - File path utility
description: |
    This module provides a small, fast utility for working with file paths. It is friendlier to use than File::Spec and provides easy access to functions from several other core file handling modules. It aims to be smaller and faster than many alternatives on CPAN, while helping people do many common things in consistent and less error-prone ways.
builddeps  :
    - perl-test-mockrandom
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
