name       : perl-path-tiny
version    : '0.144'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Path-Tiny-0.144.tar.gz : f6ea094ece845c952a02c2789332579354de8d410a707f9b7045bd241206487d
license    : Apache-2.0
component  : programming.perl
homepage   : https://metacpan.org/pod/Path::Tiny
summary    : Path::Tiny - File path utility
description: |
    This module provides a small, fast utility for working with file paths. It is friendlier to use than File::Spec and provides easy access to functions from several other core file handling modules. It aims to be smaller and faster than many alternatives on CPAN, while helping people do many common things in consistent and less error-prone ways.
builddeps  :
    - perl-test-mockrandom
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
