name       : perl-path-tiny
version    : 0.104
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Path-Tiny-0.104.tar.gz : c69f1dcfeb4aa004086deb9bc14c7d79f45798b947f1efbd634a3442e267aaef
license    : Apache-2.0
component  : programming.perl
summary    : Path::Tiny - File path utility
description: |
    This module provides a small, fast utility for working with file paths. It is friendlier to use than File::Spec and provides easy access to functions from several other core file handling modules. It aims to be smaller and faster than many alternatives on CPAN, while helping people do many common things in consistent and less error-prone ways.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
