name       : perl-path-tiny
version    : '0.106'
release    : 2
source     :
    - https://github.com/dagolden/Path-Tiny/archive/release-0.106.tar.gz : 8baa13d5a59d48ed8d98a2b53492bf3c044735308dfcdcbc9555f78bdc8baeb5
license    : Apache-2.0
component  : programming.perl
homepage   : https://github.com/dagolden/Path-Tiny
summary    : Path::Tiny - File path utility
description: |
    This module provides a small, fast utility for working with file paths. It is friendlier to use than File::Spec and provides easy access to functions from several other core file handling modules. It aims to be smaller and faster than many alternatives on CPAN, while helping people do many common things in consistent and less error-prone ways.
builddeps  :
    - perl-test-mockrandom
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
